Задание к уроку "Rack-интерфейс"
dastanabeuov/rack pull request #1
Opened 2019-02-21 09:33 UTC by dastanabeuov

В отдельном резпозитории напишите минималистичное Rack приложение которое будет отвечать на  
URL GET /time
с параметром строки запроса format и возвращать время в заданном формате. 

Например, GET-запрос  
/time?format=year%2Cmonth%2Cday
вернет ответ с типом text/plain и телом 1970-01-01.

Доступные форматы времени: year, month, day, hour, minute, second
Форматы передаются в параметре строки запроса format в любом порядке
Если среди форматов времени присутствует неизвестный формат, необходимо возвращать ответ с кодом статуса 400 и телом "Unknown time format [epoch]"
Если неизвестных форматов несколько, все они должны быть перечислены в теле ответа, например: "Unknown time format [epoch, age]"
При запросе на любой другой URL необходимо возвращать ответ с кодом статуса 404

Ответ к заданию должен быть в виде открытого пулл-реквеста.

2019-02-21 16:47 UTC, iBublik requested changes

2019-02-21 16:47 UTC, iBublik commented on app.rb
> +  TIME_PATH = "/time"
Ну такое уж пихать в константы - перебор

2019-02-21 16:47 UTC, iBublik commented on app.rb
> +    response = Rack::Response.new
В принципе у нас все просто, можно было обычный rack-совместимый массив возвращать

2019-02-21 16:47 UTC, iBublik commented on app.rb
> +    response.body[0][0..6] == "Unknown" ? response.status = 200 : response.status = 400
Слишком хрупко. Захочется поменять возвращаемый текст - придется и тут переписывать.

2019-02-21 16:47 UTC, iBublik commented on app.rb
> +    params.keys.include?(FORMAT_QUERY_BEGIN) && params['format']
Зачем такая сложная проверка, зачем константа?
`params.key?('format')` проверит что в параметрах есть нужный ключ. Если хочется более надежной проверки, можно так `Array(params['format']).any?`

2019-02-21 16:47 UTC, iBublik commented on application/time_calculator.rb
> +    @time = time.split(',')
Это не time, это formats

2019-02-21 16:47 UTC, iBublik commented on application/time_calculator.rb
> +  TIME_FORMATS = ["year", "month", "day", "hour", "min", "sec"]
`KNOWN_FORMATS = %w[year month day hour min sec]`

2019-02-21 16:47 UTC, iBublik commented on application/time_calculator.rb
> +  def form_time_string
Зачем все в один метод лепить? Сделай лучше несколько. `valid?` - все ли параметры верны, `unknown_formats` - список неверных форматов, `formatted_time` - отформатированное время

2019-02-21 16:47 UTC, iBublik commented on application/time_calculator.rb
> +    return ("Unknown time format: #{unknown_formats}\n") if unknown_formats.any?
Не надо в этом классе никаких сообщений формировать, пусть этим App занимается

2019-02-21 16:47 UTC, iBublik commented on application/time_calculator.rb
> +      final_string += "#{ Time.now.send(t) }-"
Представь что добавится новый формат - `short_year`. У Time нет такого метода, как ты его вернешь?
Для форматирования времени есть метод strftime

2019-02-22 07:36 UTC, dastanabeuov commented on app.rb
> +  TIME_PATH = "/time"
исправил

2019-02-22 07:37 UTC, dastanabeuov commented on app.rb
> +    response = Rack::Response.new
через Rack::Request.new(env) все время падает...

2019-02-22 08:45 UTC, dastanabeuov commented on application/time_calculator.rb
> +    return ("Unknown time format: #{unknown_formats}\n") if unknown_formats.any?
ок

2019-02-22 08:47 UTC, dastanabeuov commented on application/time_calculator.rb
> +      final_string += "#{ Time.now.send(t) }-"
так ведь возвращается строка(year-month-day) а через метод send возвращается(2019.02.22)

В чем подвох?

2019-02-22 08:48 UTC, dastanabeuov commented on application/time_calculator.rb
> +  def form_time_string
исправил сделал отдельные методы...код в form_time_string стал проще

2019-02-22 08:49 UTC, dastanabeuov commented on application/time_calculator.rb
> +  TIME_FORMATS = ["year", "month", "day", "hour", "min", "sec"]
исправил все время забываю про идиомы и стиль в РУБИ

2019-02-22 08:49 UTC, dastanabeuov commented on application/time_calculator.rb
> +    @time = time.split(',')
да точно исправил

2019-02-22 08:50 UTC, dastanabeuov commented on app.rb
> +    params.keys.include?(FORMAT_QUERY_BEGIN) && params['format']
мне понравился метод params.key?('format') исправил на этот

2019-02-22 08:51 UTC, dastanabeuov commented on app.rb
> +    response.body[0][0..6] == "Unknown" ? response.status = 200 : response.status = 400
исправил оставил предпочтение методу...так даже лучше

2019-02-22 08:51 UTC, dastanabeuov commented on app.rb
> +    response = Rack::Response.new
Ясно буду знать

2019-02-22 08:52 UTC, dastanabeuov commented on app.rb
> +  TIME_PATH = "/time"
В коде хорошо смотриться....исправил убрал вообще

2019-02-23 07:42 UTC, iBublik requested changes

2019-02-23 07:42 UTC, iBublik commented on app.rb
> +    response = Rack::Response.new
Просто текущий вариант выглядит усложнением. Приходится `response.finish` вызывать

2019-02-23 07:42 UTC, iBublik commented on app.rb
> +  def has_format_params?(params)
И зачем это в метод выделять? Все же тривиально. И не переиспользуется нигде

2019-02-23 07:42 UTC, iBublik commented on app.rb
> +    response.body == calculator.unknown_formats ? response.status = 200 : response.status = 400
Первые секунд 10 я вообще не понимал что тут происходит :)
Зачем так усложнять? Сделай проще
```ruby
if calculator.valid?
  response.status = 200
  response.body.push(calculator.fomratted_time)
else
  response.status = 400
  response.body.push(calculator.unknown_formats)
end
```

2019-02-23 07:42 UTC, iBublik commented on application/time_calculator.rb
> +    @unknown_formats = []
Ты уже в конструкторе можешь задать неверные параметры

2019-02-23 07:42 UTC, iBublik commented on application/time_calculator.rb
> +    @format_time = ''
Зачем это делать инстанс переменной?

2019-02-23 07:42 UTC, iBublik commented on application/time_calculator.rb
> +  def form_time_string
У тебя все равно есть универсальный метод, который все подряд делает. Убери его, он только усложняет все

2019-02-23 07:42 UTC, iBublik commented on application/time_calculator.rb
> +  def valid? #все ли параметры верны
Методы-предикаты просто возвращают логическое значение. У тебя он заполняет массив и возвращает его же, это нарушает все конвенции

2019-02-23 07:42 UTC, iBublik commented on application/time_calculator.rb
> +    @formats.each { |t| @unknown_formats.push(t) unless KNOWN_FORMATS.include?(t) }
Для фильтрации коллекций существует метод `select`

2019-02-23 07:42 UTC, iBublik commented on application/time_calculator.rb
> +    @formats.each { |t| @format_time += "#{ Time.now.strftime(t) }-" }
1. Посмотри в документации как использовать strftime - https://devdocs.io/ruby~2.5/time#method-i-strftime. У тебя передаются неверные форматы
2. Не надо в цикле вызывать Time.now. Сначала сформируй итоговый формат, потом уже 1 раз вызови `Time.now.strftime(format)`
3. Чтоб не приходилось убирать `-` в конце строки, используй метод `join` массива.

2019-02-23 07:42 UTC, iBublik commented on application/time_calculator.rb
> +    @format_time.chop! + "\r\n"
Просто вернит отформатированное время. Переносы строк пускай добавляет вызывающий код

2019-02-23 16:27 UTC, dastanabeuov commented on app.rb
> +  def has_format_params?(params)
Да точно испарвил...

2019-02-23 16:37 UTC, dastanabeuov commented on app.rb
> +    response.body == calculator.unknown_formats ? response.status = 200 : response.status = 400
хорошо исправил свой говно код :-)

2019-02-23 16:41 UTC, dastanabeuov commented on application/time_calculator.rb
> +    @format_time = ''
чтобы [тут](formatted_time) использовать

2019-02-23 17:06 UTC, dastanabeuov commented on application/time_calculator.rb
> +    @formats.each { |t| @unknown_formats.push(t) unless KNOWN_FORMATS.include?(t) }
применил и исправил

2019-02-23 17:53 UTC, dastanabeuov commented on application/time_calculator.rb
> +  def valid? #все ли параметры верны
bcghfdbk

2019-02-23 17:56 UTC, dastanabeuov commented on application/time_calculator.rb
> +    @formats.each { |t| @unknown_formats.push(t) unless KNOWN_FORMATS.include?(t) }
изменил

2019-02-24 07:44 UTC, iBublik requested changes

2019-02-24 07:44 UTC, iBublik commented on application/time_calculator.rb
> +  KNOWN_FORMATS = %w[year month day hour min sec]
В этом больше нет особого смысла. Чтобы получить все известные форматы `FORMATTED_FORMAT.keys`

2019-02-24 07:44 UTC, iBublik commented on application/time_calculator.rb
> +  FORMATTED_FORMAT = {
Масло масляное

2019-02-24 07:44 UTC, iBublik commented on application/time_calculator.rb
> +    return true if @formats.select { |i| i == KNOWN_FORMATS }
Когда надо проверить, что все элементы коллекции соответствуют определенному условию, используют метод `all?`

2019-02-24 07:44 UTC, iBublik commented on application/time_calculator.rb
> +    valid?
Метод возвращает `true` или `nil`, а не список форматов

2019-02-24 07:44 UTC, iBublik commented on application/time_calculator.rb
> +    @formats.each { |t| @format_time += "#{FORMATTED_FORMAT[t]}-" }
Зачем в инстанс переменную что-то пихать? Получается, у тебя объект только 1 раз можно использовать, дальше он начинает дублировать форматы.

2019-02-24 07:44 UTC, iBublik commented on application/time_calculator.rb
> +    @formats.each { |t| @format_time += "#{FORMATTED_FORMAT[t]}-" }
`@formats.map { |format| FORMATTED_FORMAT[format] }.join('-')`

2019-02-24 07:44 UTC, iBublik commented on application/time_calculator.rb
> +    #вариант с (join) выдает ошибку | а с (.chop! + "\n") все нормально
В таких случаях надо писать как ты пытался делать и что за ошибка
Написал выше рабочий вариант

2019-02-24 09:08 UTC, dastanabeuov commented on application/time_calculator.rb
> +  KNOWN_FORMATS = %w[year month day hour min sec]
ясноубрал

2019-02-24 09:08 UTC, dastanabeuov commented on application/time_calculator.rb
> +  FORMATTED_FORMAT = {
исправил

2019-02-24 09:15 UTC, dastanabeuov commented on application/time_calculator.rb
> +    return true if @formats.select { |i| i == KNOWN_FORMATS }
применилююбуду знать

2019-02-24 09:59 UTC, dastanabeuov commented on application/time_calculator.rb
> +    valid?
да точно
изменил дописал

2019-02-24 10:02 UTC, dastanabeuov commented on application/time_calculator.rb
> +    #вариант с (join) выдает ошибку | а с (.chop! + "\n") все нормально
понял

2019-02-24 16:47 UTC, iBublik requested changes

2019-02-24 16:47 UTC, iBublik commented on application/time_calculator.rb
> +    return true if @formats.select { |i| i == FORMATTED_VERSION.keys.all? }
Ты можешь объяснить что вообще тут происходит? По коду совершенно непонятно. Рекомендую смотреть документацию метода, прежде чем начинать его использовать
Метод должен вернуть true, если все переданные форматы известны, в ином случае false.

2019-02-24 16:47 UTC, iBublik commented on application/time_calculator.rb
> +    @formats.each do |f|
И снова ты изобретаешь методы стандартной библиотеки. Метод `select` служит для фильтрации коллекций

2019-02-24 16:47 UTC, iBublik commented on application/time_calculator.rb
> +    Time.now.strftime(@formats)
В `@formats` вообще-то находится массив

2019-02-24 16:47 UTC, iBublik commented on application/time_calculator.rb
> +    @formats.map { |format| FORMATTED_VERSION[format] }.join('-')
Кажется тебе надо повторить самые первые уроки по Ruby, потому что ты явно не понимаешь что пишешь
Вот это выражение возвращает итоговый формат, который можно использовать в strftime. Но ты его никуда не сохраняешь, поэтому и использовать не можешь

2019-02-24 19:44 UTC, dastanabeuov commented on application/time_calculator.rb
> +    @formats.map { |format| FORMATTED_VERSION[format] }.join('-')
я знал что метод мап заменяет создает новый вариант данных - но не знал что его сперва нужно сохранить кудато и затем только применять(мне казалось можно сразу использовать)
Спасибо буду знать

2019-02-24 20:09 UTC, dastanabeuov commented on application/time_calculator.rb
> +    return true if @formats.select { |i| i == FORMATTED_VERSION.keys.all? }
array.select {|item| block }
Выполняет выражение в block для каждого элемента массива array и возвращает массив, который состоит из элементов, для которых выражение в block принимает значение true.

2019-02-25 07:25 UTC, iBublik commented on application/time_calculator.rb
> +    return true if @formats.select { |format| FORMATTED_VERSION.keys.include?(format) }
То же самое, но проще - `@formats.all? { |format| FORMATTED_VERSION.key?(format) }`
Еще проще - `unknown_formats.empty?`

2019-02-25 07:25 UTC, iBublik commented on application/time_calculator.rb
> +    unknown_formats = @formats.select { |format| format != FORMATTED_VERSION.keys }
Зачем ты пишешь что-то в переменную? Она уничтожается сборщиком мусора сразу после вызова метода
Нет смысла присваивать локальную переменную в методе, если она в нем не используется

2019-02-25 15:08 UTC, merged